services:

  config-server-ms:
    image: osamaelsaeed/config-server:latest
    container_name: config-server-ms
    ports:
      - 8080:8080
    depends_on:
      - service-registry
    networks:
      - microservicesNetwork
      - postgresNetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    image: osamaelsaeed/gateway:latest
    container_name: gateway
    ports:
      - 8084:8084
    depends_on:
      - service-registry
    networks:
      - microservicesNetwork
      - postgresNetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  service-registry:
    image: osamaelsaeed/service-registry:latest
    container_name: service-registry
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservicesNetwork
      - postgresNetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  company-ms:
    container_name: company-ms
    image: osamaelsaeed/company-ms:latest
    ports:
      - 8081:8081
    depends_on:
      - service-registry
      - config-server-ms
    networks:
      - microservicesNetwork
      - postgresNetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  job-ms:
    container_name: job-ms
    image: osamaelsaeed/job-ms:latest
    ports:
      - 8082:8082
    depends_on:
      - service-registry
      - config-server-ms
    networks:
      - microservicesNetwork
      - postgresNetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review-ms:
    container_name: review-ms
    image: osamaelsaeed/review-ms:latest
    ports:
      - 8083:8083
    depends_on:
      - service-registry
      - config-server-ms
    networks:
      - microservicesNetwork
      - postgresNetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: elsaeed
      POSTGRES_PASSWORD: Om3571590#
      PGDATA: /data/postgresDB
    volumes:
      - postgresDB_data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '5433:5432'
    networks:
      - postgresNetwork
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-om35453@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Om3571590#}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - postgresNetwork
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - postgresNetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - postgresNetwork

volumes:
  postgresDB_data:
  pgadmin:
networks:
  postgresNetwork:
    driver: bridge
  microservicesNetwork:
    driver: bridge